### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by yoavram** [timsainb/AVGN#5]
When importing
```
from sklearn.externals.joblib import Parallel, delayed
``` 
I get 
```
DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
```

**Comment by timsainb** [comment]
Hi @yoavram, you can import joblib directly instead of importing from sklearn if you pip install it. If you look at the examples from my newer repo from the paper (which I would recommend using if you're just starting out) you can see how to import joblib directly. https://github.com/timsainb/avgn_paper

**Comment by yoavram** [comment]
OK. The import that caused the warning is in a notebook in this repo, I'll look at the paper repo.
Thanks.
